"""Build Templates — 10 known-good physical-agent architectures.

Each template defines: allowed electronics, dimensions, clearances,
power, wiring, mounting patterns, firmware, supplier alternatives.
"""

TEMPLATES = {
    'voice_puck': {
        'name': 'Voice Puck',
        'description': 'Compact voice assistant puck with mic, speaker, RGB',
        'capabilities': ['hear', 'speak', 'wifi', 'status_light'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'inmp441_mic', 'max98357a_amp', 'speaker_3w', 'ws2812b_led'],
        'optional_modules': ['oled_096', 'touch_button'],
        'dimensions': {'min_volume_cm3': 40, 'max_volume_cm3': 120},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 18,
        'evidence': 'M5Stack ATOM Voice equivalent, proven in 50+ projects',
    },
    'display_face': {
        'name': 'Display Face',
        'description': 'Small device with OLED eyes + mic + speaker',
        'capabilities': ['hear', 'speak', 'face_expression', 'wifi'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'oled_096', 'inmp441_mic', 'max98357a_amp', 'speaker_3w'],
        'optional_modules': ['ws2812b_led', 'capacitive_touch'],
        'dimensions': {'min_volume_cm3': 50, 'max_volume_cm3': 150},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 20,
        'evidence': 'esp32-eyes + INMP441 proven pattern',
    },
    'pan_tilt_head': {
        'name': 'Pan/Tilt Head',
        'description': 'Camera or face with 2-axis movement',
        'capabilities': ['see', 'pan', 'tilt', 'wifi'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'camera_ov2640', 'sg90_servo_x2'],
        'optional_modules': ['oled_096', 'ws2812b_led'],
        'dimensions': {'min_volume_cm3': 60, 'max_volume_cm3': 200},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'medium',
        'estimated_electronics_cost': 15,
        'evidence': 'Pan/Tilt camera projects, 200+ GitHub builds',
    },
    'plant_node': {
        'name': 'Plant Node',
        'description': 'Soil moisture + light + temp + WiFi + RGB',
        'capabilities': ['soil_moisture', 'light', 'temperature', 'wifi', 'status_light'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'soil_moisture', 'bh1750', 'sht30', 'ws2812b_led'],
        'optional_modules': ['pump_relay', 'oled_096'],
        'dimensions': {'min_volume_cm3': 30, 'max_volume_cm3': 100},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 12,
        'evidence': 'smart-plant-monitor, ESPHome plant sensors',
    },
    'smart_lamp': {
        'name': 'Smart Lamp',
        'description': 'Presence-activated ambient lighting',
        'capabilities': ['presence', 'ambient_light', 'temperature', 'wifi'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'ws2812b_led_x3', 'pir_sensor', 'sht30'],
        'optional_modules': ['inmp441_mic', 'max98357a_amp'],
        'dimensions': {'min_volume_cm3': 100, 'max_volume_cm3': 500},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 10,
        'evidence': 'WLED projects, 18K+ stars',
    },
    'desk_controller': {
        'name': 'Desk Controller',
        'description': 'Physical control surface for AI agent',
        'capabilities': ['input_knob', 'input_buttons', 'display', 'wifi', 'status_light'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'rotary_encoder', 'oled_096', 'tactile_button_x2', 'ws2812b_led'],
        'optional_modules': ['inmp441_mic', 'max98357a_amp'],
        'dimensions': {'min_volume_cm3': 40, 'max_volume_cm3': 120},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 15,
        'evidence': 'M5Stack dial, various knob controllers',
    },
    'moving_camera': {
        'name': 'Moving Camera',
        'description': 'PTZ camera with tracking',
        'capabilities': ['see', 'pan', 'tilt', 'wifi', 'tracking'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'camera_ov2640', 'sg90_servo_x2', 'ws2812b_led'],
        'optional_modules': ['oled_096', 'speaker_3w'],
        'dimensions': {'min_volume_cm3': 80, 'max_volume_cm3': 250},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'medium',
        'estimated_electronics_cost': 18,
        'evidence': 'ESP32-CAM pan/tilt projects',
    },
    'mini_rover': {
        'name': 'Mini Rover',
        'description': 'Small wheeled mobile platform',
        'capabilities': ['move', 'see', 'sense', 'wifi'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'motor_driver_bts7960', 'dc_motor_x2', 'imu_mpu6050'],
        'optional_modules': ['camera_ov2640', 'ultrasonic_hcsr04', 'oled_096'],
        'dimensions': {'min_volume_cm3': 200, 'max_volume_cm3': 800},
        'power': 'battery_lipo_2s',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'medium',
        'estimated_electronics_cost': 22,
        'evidence': 'ESP32 rover projects, 100+ GitHub builds',
    },
    'pet_device': {
        'name': 'Pet Device',
        'description': 'Camera + treat dispenser + sound',
        'capabilities': ['see', 'speak', 'actuate', 'wifi'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'camera_ov2640', 'sg90_servo', 'max98357a_amp', 'speaker_3w'],
        'optional_modules': ['ws2812b_led', 'pir_sensor'],
        'dimensions': {'min_volume_cm3': 100, 'max_volume_cm3': 300},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'medium',
        'estimated_electronics_cost': 20,
        'evidence': 'pet-feeder-esphome, PetFeeder projects',
    },
    'sensor_box': {
        'name': 'Sensor Box',
        'description': 'Multi-sensor environmental monitoring station',
        'capabilities': ['temperature', 'humidity', 'light', 'air_quality', 'wifi', 'display'],
        'core': 'esp32s3',
        'required_modules': ['esp32s3', 'sht30', 'bh1750', 'mq135', 'oled_096'],
        'optional_modules': ['ws2812b_led', 'inmp441_mic'],
        'dimensions': {'min_volume_cm3': 40, 'max_volume_cm3': 120},
        'power': 'usb_c_5v',
        'enclosure_process': 'fdm_print',
        'assembly_difficulty': 'low',
        'estimated_electronics_cost': 12,
        'evidence': 'ESP32 weather stations, ESPHome sensors',
    },
}
